/* ---------------- Example lecture JSON (flat command list) ---------------- */

window.lecture = [
  {
    type: "defaults",
    font_size_px: 22,
    svg_text_font_size: 9,
    font_scale: 1.0,
    layout_split: 60,
    write_speed_chars_per_sec: 38,
    write_animate: true,
    write_appear_speed: 0.6,
    draw_speed_sec_per_100: 1.0,
    draw_animate: true,
    draw_height_px: 180,
    draw_location: "right",
    draw_coords: "svg",
    stroke_width: 1.0,
    speech_lang: "en-US",
    speech_voice: "male",
    speech_rate: 1.25,
    question_require_answer: false,
    execution_mode: "movie",
    movie_wait_seconds: 2,
    webr_show_code: true,
    webr_editable: true,
    webr_auto_run: true,
    webr_location: "left",
    webr_result_location: "right",
    webr_height: "220px",
    webr_clear_page: true,
    webr_wait_after: true,
    pyodide_show_code: true,
    pyodide_editable: true,
    pyodide_auto_run: true,
    pyodide_location: "left",
    pyodide_result_location: "right",
    pyodide_height: "220px",
    pyodide_clear_page: true,
    pyodide_wait_after: true,
    pyodide_auto_install: true,
    pyodide_preload: false,
    pause_on_click: true,
    js_show_code: false,
    js_editable: true,
    js_auto_run: true,
    js_location: "left",
    js_result_location: "right",
    js_height: "220px",
    js_clear_page: true,
    js_wait_after: true,
    allow_html: false,
    p5_width: "100%",
    p5_height: "240px",
    p5_location: "right",
    p5_autorun: true,
    p5_controls: false,
    p5_auto_resize: true,
    p5_clear_page: false,
    p5_wait_after: false,
  },
  { type: "defaults", write_speed_chars_per_sec: 34, font_size_px: 22, question_require_answer: true },
    { type: "new_page", title: "Demand, supply, and equilibrium" },
    { type: "write_speak", id: "intro1", markdown: "**Demand** shows how much <box>buyers</box> want at each price. <underline color=\"#f59e0b\">Supply</underline> shows how much sellers offer." },
    { type: "write_speak", id: "intro2", markdown: "Where demand and supply cross, we get the <box color=\"#60a5fa\">market price</box> and <highlight color=\"rgba(34,197,94,.35)\">quantity</highlight>. <note>At equilibrium, there is no excess demand or supply.</note>" },
    { type: "new_drawing",
      id: "fig1",
      title: "**Figure 1.** Demand & supply",
      subtitle: "Equilibrium occurs at the intersection.",
      size: 200
    },
    { type: "draw", cmd: "line", x1: 12, y1: 12, x2: 12, y2: 88, class: "stroke", stroke_width: 1.3, id: "axisY" },
    { type: "draw", cmd: "line", x1: 12, y1: 12, x2: 92, y2: 12, class: "stroke", stroke_width: 1.3, id: "axisX" },
    { type: "draw", cmd: "text", x: 8, y: 88, text: "Price", rotation: -90, color: "var(--muted)" },
    { type: "draw", cmd: "text", x: 92, y: 8, text: "Quantity", color: "var(--muted)", anchor: "end" },
    { type: "draw", cmd: "line", x1: 16, y1: 84, x2: 88, y2: 24, id: "D", class: "stroke", stroke_width: 1.5, stroke: "#f59e0b",
      label: "D", label_location: "right", speak: "Demand slopes down." },
    { type: "draw", cmd: "line", x1: 18, y1: 20, x2: 88, y2: 82, id: "S", class: "stroke", stroke_width: 1.5, stroke: "#22c55e",
      label: "S", label_location: "right", speak: "Supply slopes up." },
    { type: "draw", cmd: "line", x1: 12, y1: 52, x2: 64, y2: 52, class: "stroke guide", stroke_width: 1.1, id: "priceLine",
      label: "P*", label_location: "right" },
    { type: "draw", cmd: "line", x1: 64, y1: 12, x2: 64, y2: 52, class: "stroke guide", stroke_width: 1.1, id: "qtyLine",
      label: "Q*", label_location: "under" },
    { type: "write", id: "noteEq", markdown: "At **P*** and **Q***, buyers and sellers agree on a trade.", muted: true, font_size_px: 20 },
    { type: "wait", click: true, label: "Continue to surplus intuition." },
    { type: "new_page", title: "Consumer and producer surplus" },
    { type: "write_speak", id: "csDef", markdown: "**Consumer surplus** is the value buyers get above the price they pay." },
    { type: "write_speak", id: "psDef", markdown: "**Producer surplus** is the value sellers get above their cost." },
    { type: "new_drawing",
      id: "fig2",
      title: "**Figure 2.** Surplus areas",
      subtitle: "Above price = consumer surplus, below price = producer surplus.",
      footnote: "_Think of it as two triangles around the price line._",
      size: 210
    },
    { type: "draw", cmd: "line", x1: 12, y1: 12, x2: 12, y2: 88, class: "stroke", stroke_width: 1.3 },
    { type: "draw", cmd: "line", x1: 12, y1: 12, x2: 92, y2: 12, class: "stroke", stroke_width: 1.3 },
    { type: "draw", cmd: "line", x1: 16, y1: 84, x2: 88, y2: 24, class: "stroke", stroke_width: 1.5, stroke: "#f59e0b", label: "D", label_location: "right" },
    { type: "draw", cmd: "line", x1: 18, y1: 20, x2: 88, y2: 82, class: "stroke", stroke_width: 1.5, stroke: "#22c55e", label: "S", label_location: "right" },
    { type: "draw", cmd: "line", x1: 12, y1: 52, x2: 64, y2: 52, class: "stroke guide", stroke_width: 1.1, label: "P*", label_location: "right" },
    { type: "draw", cmd: "line", x1: 64, y1: 12, x2: 64, y2: 52, class: "stroke guide", stroke_width: 1.1, label: "Q*", label_location: "under" },
    { type: "draw", cmd: "polygon", points: [ [12,52], [64,52], [12,84] ], class: "shade", fill: "rgba(96,165,250,.28)", animate: "fade",
      id: "csArea", label: "CS", label_location: "center", speak: "This upper triangle is consumer surplus." },
    { type: "draw", cmd: "polygon", points: [ [18,20], [64,52], [18,52] ], class: "shade", fill: "rgba(34,197,94,.28)", animate: "fade",
      id: "psArea", label: "PS", label_location: "center", speak: "This lower triangle is producer surplus." },
    { type: "highlight", id: "csArea", color: "rgba(34,197,94,.8)" },
    { type: "highlight", id: "psArea", color: "rgba(96,165,250,.8)" },
    { type: "write_speak", id: "intuition1", markdown: "Intuition: buyers with higher willingness‑to‑pay gain more; sellers with lower costs gain more." },
    { type: "write", id: "example1", markdown: "**Example:** If a concert ticket sells for $50, someone willing to pay $80 gets $30 in consumer surplus.", muted: true, font_size_px: 20 },
    { type: "question",
      draw_commands: [
        { type: "new_drawing", location: "right", title: "**Figure 3.** Identify the surplus area", size: 170 },
        { cmd: "line", x1: 12, y1: 12, x2: 92, y2: 12, class: "stroke" },
        { cmd: "line", x1: 12, y1: 12, x2: 12, y2: 88, class: "stroke" },
        { cmd: "line", x1: 16, y1: 84, x2: 88, y2: 24, class: "stroke" },
        { cmd: "line", x1: 18, y1: 20, x2: 88, y2: 82, class: "stroke" },
        { cmd: "line", x1: 12, y1: 52, x2: 64, y2: 52, class: "stroke guide" },
        { cmd: "polygon", points: [ [12,52], [64,52], [12,84] ], class: "shade", animate: "fade", fill: "rgba(96,165,250,.28)" }
      ],
      markdown: "**Quick check:** Which area is consumer surplus?",
      choices: ["Triangle above the price", "Triangle below the price", "Rectangle under the price"],
      correct_index: 0
    },
    { type: "new_page", title: "WebR examples" },
    { type: "write", markdown: "**Example 1:** Simple calculation (code left, result right)." },
    { type: "webr",
      code: "x <- rnorm(100)\nmean(x)\nsummary(x)",
      auto_run: true,
      show_code: true,
      editable: true,
      location: "left",
      result_location: "right"
    },
    { type: "write", markdown: "**Example 2:** Plot (code left, plot right)." },
    { type: "webr",
      code: "x <- rnorm(200)\nhist(x, col='steelblue', main='Histogram')",
      auto_run: true,
      show_code: true,
      editable: true,
      location: "left",
      result_location: "right"
    },
    { type: "write", markdown: "**Example 3:** ggplot2 + dplyr (dataframe + plot)." },
    { type: "webr",
      code: "library(dplyr)\nlibrary(ggplot2)\n\ndf <- tibble(x = rnorm(200)) %>% mutate(bin = cut(x, breaks=10))\nsummary_df <- df %>% count(bin)\nprint(summary_df)\n\nggplot(df, aes(x)) + geom_histogram(fill='tomato', bins=12) + theme_minimal()",
      auto_run: true,
      show_code: true,
      editable: true,
      location: "left",
      result_location: "right"
    },
    { type: "write", markdown: "**Example 4:** Output only (code hidden)." },
    { type: "webr",
      code: "mean(1:10)",
      auto_run: true,
      show_code: false,
      location: "left",
      wait_after: false,
      clear_page: false
    },
    { type: "new_page", title: "Pyodide examples" },
    { type: "pyodide_preload" },
    { type: "write", markdown: "**Example 1:** Simple Python calculation." },
    { type: "pyodide",
      code: "import math\nsum([math.sqrt(x) for x in range(1, 10)])",
      auto_run: true,
      show_code: true,
      editable: true,
      location: "left",
      result_location: "right"
    },
    { type: "write", markdown: "**Example 2:** DataFrame + plot (matplotlib)." },
    { type: "pyodide",
      code: "import pandas as pd\nimport matplotlib.pyplot as plt\n\ndf = pd.DataFrame({'x': list(range(20))})\ndf['y'] = df['x']**2\nprint(df.head())\nplt.plot(df['x'], df['y'])\nplt.title('y = x^2')",
      auto_run: true,
      show_code: true,
      editable: true,
      location: "left",
      result_location: "right"
    },
    { type: "write", markdown: "**Example 3:** Output only (code hidden)." },
    { type: "pyodide",
      code: "sum(range(1, 101))",
      auto_run: true,
      show_code: false,
      location: "left",
      wait_after: false,
      clear_page: false
    },
    { type: "new_page", title: "Interactive p5.js example" },
    { type: "write", markdown: "A simple interactive sketch: drag to move the ball and watch it bounce." },
    { type: "p5",
      id: "p5-bounce",
      height: "240px",
      location: "right",
      sketch: `
let x = 80, y = 80;
let vx = 2.2, vy = 1.6;
function setup() {
  createCanvas(container.clientWidth || 320, container.clientHeight || 200);
}
function draw() {
  background(245);
  x += vx; y += vy;
  if (x < 20 || x > width - 20) vx *= -1;
  if (y < 20 || y > height - 20) vy *= -1;
  fill(59, 130, 246);
  noStroke();
  circle(x, y, 40);
}
function mouseDragged() {
  x = mouseX; y = mouseY;
}
`
    }
];
